# (PART) **yaml** {-}

# yaml Setup {.tabset}

yaml metadata determines the output file format, looking, and any other additional customizing features of Rmarkdown files.  

## HTML Document

```{yaml}
title: "R Markdown Features"
subtitle: "A Compact Reference"
author: "[Yongfu Liao](https://liao961120.github.io/)"
date: "`r format(Sys.Date(), '%B %e, %Y')`" 
#bibliography: ref.bib
#csl: apa.csl
link-citations: yes
output:
  bookdown::html_document2:
    css: style.css
    code_folding: show
    df_print: kable
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: yes
```


## PDF Document

```{yaml}
title: "A PDF document YAML Frontmatter"
author: "廖永賦\\thanks{組別：3 ~~ 系級：心理三 ~~ 學號：B00000000}"
date: "`r format(Sys.Date(), '%B %e, %Y')`"
#bibliography: ref.bib
#csl: apa.csl
documentclass: article
urlcolor: "blue"
fontsize: 12pt 
geometry: a4paper, headheight=0pt, margin=0.4in
linestretch: 1.35
links-as-notes: true
output:
  bookdown::pdf_document2:
    latex_engine: xelatex
    number_sections: no
    toc: no
    includes:
      in_header: header.tex
```

This is the yaml header for `bookdown::pdf_document2` output. Using `bookdown` extensions have several advantages. Search 'bookdown' for details.

You may need to attatch an additional `header.tex` and set `latex_engine` to `xelatex` for PDF documents containing multibite characters (e.g. Chinese). Read more about  [header.txt](#pdf-header).


Note that Latex only accepts fontsize of 10pt, 11pt, or 12pt. See [this](https://github.com/rstudio/rmarkdown/issues/878) for more detail.


## PDF: header.tex {#pdf-header}

The code below is for generating PDF documents written in (Traditional) Chinese.

```tex
`r paste(readLines("~/local_depend/style_sheets/header.tex"), collapse = '\n')`
```

## PDF: template {#pdf-template}

```markdown
output:
  pdf_document:
    template: two-col.latex
    includes:
      in_header: header.tex
```

It is possible to define [custom latex template](https://rmarkdown.rstudio.com/pdf_document_format#custom_templates).
For example, [`two-col.latex`](https://github.com/liao961120/local_depend/blob/master/style_sheets/two-col.latex) is created by putting the variable `body` (which is the rendered content of the Rmd file) inside `multicols` latex extension:

```tex
\begin{multicols}{2}
$body$
\end{multicols}
```

## Bibliography

```{yaml}
bibliography: ./citation/neanderthals.bib
csl: ./citation/apa.csl # APA style sheet
link-citations: yes
```

For citation syntax, read the section [Bibliography & Citations](#cite).
