# Printing Bookdown to PDF

Although bookdown nicely provides options to render the book to PDF formats, setting up things related to LaTeX can still be demanding, especially for people not familiar with LaTeX. To make bookdown nicely render elements properly to both HTML and PDF also takes some additional efforts. You have to make sure not to use pure HTML or LaTeX commands in Rmd files.

One possible solution is to forget about LaTeX and use HTML compatible syntax entirely. The PDF can then be generated by using the web browser to print the web page. Currently, I found Firefox working better than Chrome in printing nicer appearance of the PDF (e.g., page break before H1 titles).

To achieve this, one has to make all chapters output to one single HTML file and specify some additional CSS styles to tweak the appearance of PDF. 

Tweak the appearance of PDF by specifying `@media print` in `style.css`[^media_print]:

```css
@media print {
  div.level1 { 
    page-break-before: always;}
  img {
    display: block;
  }
  img, table, ul, ol, .code-snippet, blockquote, pre {
      page-break-inside: avoid;
  }
}
```

and include the CSS in `_output.yml`:

```yaml
bookdown::gitbook:
  css: style.css
```

Then compile the book with `bookdown::render_book()`,
the option `output_options` takes a list as input, which overrides the options specified in `_output.yml`[^output_options]:
```{r eval=FALSE}
bookdown::render_book(
    "index.Rmd", output_file = 'single.html',
    output_format = "bookdown::gitbook",
    output_options = list(split_by = "none")
    )
```



[^media_print]: Note that `page-break-before: always` doesn't seem to work in Chrome, and `img { page-break-inside: avoid; }` doesn't work on Firefox (so some images get cut into parts), at least on my computer.


[^output_options]: For example, one can set
    ```yaml
    bookdown::gitbook:
      split_by: chapter
    ```
    so that the default output is for reading on the web (separated HTML files are quicker to load). 
    
    For printing, one can override the default by passing `output_options(list(split_by = "none"))` to `bookdown::render_book()` to get a single HTML output file.